name: boshqa_dunyo_ostonasi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.15.3
  firebase_storage: ^11.6.4
  equatable: ^2.0.5
  go_router: ^15.1.2
  get_it: ^7.6.7
  intl: ^0.18.1
  google_sign_in: ^6.2.1
  line_icons: ^2.0.3
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.0
  flutter_pdfview: ^1.3.2
  http: ^1.2.1
  path_provider: ^2.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Handlee
      fonts:
        - asset: fonts/Handlee.ttf